// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/wb_parser.proto

package wbparser

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WBParser_GetPrice_FullMethodName = "/wbparser.WBParser/GetPrice"
)

// WBParserClient is the client API for WBParser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WBParserClient interface {
	GetPrice(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type wBParserClient struct {
	cc grpc.ClientConnInterface
}

func NewWBParserClient(cc grpc.ClientConnInterface) WBParserClient {
	return &wBParserClient{cc}
}

func (c *wBParserClient) GetPrice(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, WBParser_GetPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WBParserServer is the server API for WBParser service.
// All implementations must embed UnimplementedWBParserServer
// for forward compatibility.
type WBParserServer interface {
	GetPrice(context.Context, *BatchRequest) (*BatchResponse, error)
	mustEmbedUnimplementedWBParserServer()
}

// UnimplementedWBParserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWBParserServer struct{}

func (UnimplementedWBParserServer) GetPrice(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (UnimplementedWBParserServer) mustEmbedUnimplementedWBParserServer() {}
func (UnimplementedWBParserServer) testEmbeddedByValue()                  {}

// UnsafeWBParserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WBParserServer will
// result in compilation errors.
type UnsafeWBParserServer interface {
	mustEmbedUnimplementedWBParserServer()
}

func RegisterWBParserServer(s grpc.ServiceRegistrar, srv WBParserServer) {
	// If the following call pancis, it indicates UnimplementedWBParserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WBParser_ServiceDesc, srv)
}

func _WBParser_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WBParserServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WBParser_GetPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WBParserServer).GetPrice(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WBParser_ServiceDesc is the grpc.ServiceDesc for WBParser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WBParser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wbparser.WBParser",
	HandlerType: (*WBParserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrice",
			Handler:    _WBParser_GetPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wb_parser.proto",
}
