// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/wb_parser.proto

package wbparser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NmIds         []int32                `protobuf:"varint,1,rep,packed,name=nm_ids,json=nmIds,proto3" json:"nm_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_proto_wb_parser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wb_parser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_wb_parser_proto_rawDescGZIP(), []int{0}
}

func (x *BatchRequest) GetNmIds() []int32 {
	if x != nil {
		return x.NmIds
	}
	return nil
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NmId          int32                  `protobuf:"varint,1,opt,name=nm_id,json=nmId,proto3" json:"nm_id,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_proto_wb_parser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wb_parser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_wb_parser_proto_rawDescGZIP(), []int{1}
}

func (x *ProductResponse) GetNmId() int32 {
	if x != nil {
		return x.NmId
	}
	return 0
}

func (x *ProductResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ProductResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_proto_wb_parser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wb_parser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_wb_parser_proto_rawDescGZIP(), []int{2}
}

func (x *BatchResponse) GetResults() []*ProductResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_wb_parser_proto protoreflect.FileDescriptor

const file_proto_wb_parser_proto_rawDesc = "" +
	"\n" +
	"\x15proto/wb_parser.proto\x12\bwbparser\"%\n" +
	"\fBatchRequest\x12\x15\n" +
	"\x06nm_ids\x18\x01 \x03(\x05R\x05nmIds\"f\n" +
	"\x0fProductResponse\x12\x13\n" +
	"\x05nm_id\x18\x01 \x01(\x05R\x04nmId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"D\n" +
	"\rBatchResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.wbparser.ProductResponseR\aresults2G\n" +
	"\bWBParser\x12;\n" +
	"\bGetPrice\x12\x16.wbparser.BatchRequest\x1a\x17.wbparser.BatchResponseB\fZ\n" +
	"./wbparserb\x06proto3"

var (
	file_proto_wb_parser_proto_rawDescOnce sync.Once
	file_proto_wb_parser_proto_rawDescData []byte
)

func file_proto_wb_parser_proto_rawDescGZIP() []byte {
	file_proto_wb_parser_proto_rawDescOnce.Do(func() {
		file_proto_wb_parser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wb_parser_proto_rawDesc), len(file_proto_wb_parser_proto_rawDesc)))
	})
	return file_proto_wb_parser_proto_rawDescData
}

var file_proto_wb_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_wb_parser_proto_goTypes = []any{
	(*BatchRequest)(nil),    // 0: wbparser.BatchRequest
	(*ProductResponse)(nil), // 1: wbparser.ProductResponse
	(*BatchResponse)(nil),   // 2: wbparser.BatchResponse
}
var file_proto_wb_parser_proto_depIdxs = []int32{
	1, // 0: wbparser.BatchResponse.results:type_name -> wbparser.ProductResponse
	0, // 1: wbparser.WBParser.GetPrice:input_type -> wbparser.BatchRequest
	2, // 2: wbparser.WBParser.GetPrice:output_type -> wbparser.BatchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_wb_parser_proto_init() }
func file_proto_wb_parser_proto_init() {
	if File_proto_wb_parser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wb_parser_proto_rawDesc), len(file_proto_wb_parser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wb_parser_proto_goTypes,
		DependencyIndexes: file_proto_wb_parser_proto_depIdxs,
		MessageInfos:      file_proto_wb_parser_proto_msgTypes,
	}.Build()
	File_proto_wb_parser_proto = out.File
	file_proto_wb_parser_proto_goTypes = nil
	file_proto_wb_parser_proto_depIdxs = nil
}
